ssss

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -62,3 +62,29 @@ jobs:
             args: release --clean --release-notes release.md
           env:
             GITHUB_TOKEN: ${{ secrets.TOKEN }}
+    
+        - name: Install SSH key
+          env:
+            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          run: |
+            mkdir -p ~/.ssh
+            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+            chmod 600 ~/.ssh/id_rsa
+            ssh-keyscan -H fileserver.clustercat.com >> ~/.ssh/known_hosts
+    
+        - name: Test SSH connection
+          run: |
+            if ssh -o BatchMode=yes -o StrictHostKeyChecking=no -T root@fileserver.clustercat.com; then
+              echo "SSH connection successful"
+            else
+              echo "SSH connection failed"
+              exit 1
+            fi
+    
+        - name: Upload to server
+          env:
+            UPLOAD_PATH_VERSION: /var/www/files/qa/netclient-test-${{ github.event.inputs.version }}
+          run: |
+            ssh root@fileserver.clustercat.com "mkdir -p $UPLOAD_PATH_VERSION"
+            cd dist
+            find . -type f -name "netclient-*" -exec scp {} root@fileserver.clustercat.com:$UPLOAD_PATH_VERSION/ \;
